services:
  your-container-name:
    image: "${SERVICE_NAME}"
    container_name: "${SERVICE_NAME}"
    restart: unless-stopped
    environment: 
      VITE_BACKEND_URL: "${BACKEND_URL}"
    expose:
      - "80"